### PR TITLE
Issue 43

### PR DESCRIPTION
**Pull request by Wallart**

### CODE REVIEW

**Comment by Hunsu** [comment]
Rebase this branch on my branch (issue-50). You have two commits that breaks the tests. You should also split  d2e582f

**Comment by Wallart** [comment]
Issue-43 has been sanitized.
Ok, I'm going to rebase over your branch to include JSON Marshaller

**Comment by Wallart** [comment]
Rebase on issue-50 is quite problematic, reintroduces obsolete code without firing any conflicts (reintroduces stubbing, old model, etc...)

**Comment by Hunsu** [comment]
> Rebase on issue-50 is quite problematic, reintroduces obsolete code without firing any conflicts (reintroduces stubbing, old model, etc...)

What you should do is to move #52 and #53 to their own branch. #53 should be renamed. If you want I can do the rebase.

**Comment by Wallart** [comment]
Yes you should do the rebase, you are more experienced with that, I'm going to make mistakes

**Pull request merged**
