### PR TITLE
Issue 57

### PR DESCRIPTION
**Pull request by Hunsu**

### CODE REVIEW

**Comment by kelto** [comment]
seems good. Just to know (i have really no idea), you're sure the marshmaller should be registered in the bootstrap.groovy ?

**Comment by Wallart** [comment]
I think each marshmaller config should be defined in their respective controllers

**Comment by kelto** [comment]
Do you have any documentation on that ? (how to do it, best practice ?)

**Comment by Wallart** [comment]
Nope.
But imagine a situation where we have to modify the format of a JSON response.
The present configuration would imply a modification on 2 files (Bootstrap.groovy and MyController.json) instead of one file (MyController.json)

**Comment by kelto** [comment]
Could be specific class (LightPlanet, Planet, PlanetDesc, etc ...) and each marshmaller specify what to set in theses object. 
Maybe there is a way to specify the marshmaller to use, but register all of them in the Bootstrap.groovy. Honestly i don't know.

**Comment by Hunsu** [comment]
> seems good. Just to know (i have really no idea), you're sure the marshmaller should be registered in the bootstrap.groovy ?

The registration must be executed at the start up of the application so that's I put the code in the Bootstrap.

> But imagine a situation where we have to modify the format of a JSON response.
> The present configuration would imply a modification on 2 files (Bootstrap.groovy and MyController.json) instead of one file (MyController.json)

No you just need to modify your marshaller. 

> Maybe there is a way to specify the marshaller to use, but register all of them in the Bootstrap.groovy. Honestly i don't know.

Another way is to create a file that contain the marshallers and register it in Bootstrap. Now we don't have many marshallers so I just put the marshaller there.

**Pull request closed without merging**
